#!/usr/bin/env bash

function has_pacman() {
	which pacman >> /dev/null 2>&1
}

if ! has_pacman; then
	echo "You don't have pacman installed... BTW, is this even arch?"

	exit 1
fi

default() {
	echo -e "Small wrapper around pacman\n"

	echo "Choose one of:"
	echo -e " - i|install <args>"
	echo -e " - s|search  <args>"
	echo -e " - u|update  <args>"
	echo -e " - r|remove  <args>"
}

install() {
	sudo pacman -S "$@"
}

search() {
	pacman -Ss "$@"
}

update() {
	sudo pacman -Syu
}

remove() {
	sudo pacman -R "$@"
}

if [ $# -lt 1 ]; then
	default
elif [ $1 = "install" ] || [ $1 = "i" ]; then
	install "${@:2}"
elif [ $1 = "search" ] || [ $1 = "s" ]; then
	search "${@:2}"
elif [ $1 = "update" ] || [ $1 = "u" ]; then
	update
elif [ $1 = "remove" ] || [ $1 = "r" ]; then
	remove "${@:2}"
else
	default
fi

