#!/usr/bin/env bash

function has_pacman() {
	which pacman >> /dev/null 2>&1
}

if ! has_pacman; then
	echo "You don\'t have pacman installed... BTW, is this even arch?"
fi

function default() {
	echo -e "Small wrapper around pacman\n"

	echo "Choose one of:"
	echo -e " - install <args>"
	echo -e " - search  <args>"
	echo -e " - update  <args>"
	echo -e " - remove  <args>"
}

function install() {
	sudo pacman -S "$@"
}

function search() {
	pacman -Ss "$@"
}

function update() {
	sudo pacman -Syu
}

function remove() {
	sudo pacman -R "$@"
}

if [ $# -lt 1 ]; then
	default
elif [ $1 = "install" ] || [ $1 = "i" ]; then
	install "${@:2}"
elif [ $1 = "search" ] || [ $1 = "s" ]; then
	search "${@:2}"
elif [ $1 = "update" ]; || [ $1 = "u" ] then
	update
elif [ $1 = "remove" ]; || [ $1 = "r" ] then
	remove "${@:2}"
else
	default
fi

