all:
  children:
    develop:
      hosts:
        localhost:
          user_home: /home/twiglight
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
    vms:
      hosts:
        docker-hosts:
          user_home: /home/chief
          ansible_user: chief
          ansible_host: 10.0.3.193
      vars:
        ansible_connection: ssh
