#! /usr/bin/env bash

function has_zypper() {
	which zypper >> /dev/null 2>&1
}

if ! has_zypper; then
	echo "You don't have zypper installed... is this even openSUSE?"

	exit 1
fi

default() {
	echo -e "Small wrapper around zypper\n"

	echo -e "Choose one of:"
	echo -e " - i|install <args>"
	echo -e " - s|search <args>"
	echo -e " - u|update [-a|--affected]"
	echo -e " - refresh"
}

update() {
	if [ "$1" = "--affected" ] || [ "$1" = "-a" ]; then
		sudo zypper ps -s
	else
		sudo zypper update
	fi
}

if [ "$#" -lt 1 ]; then
	default
elif [ "$1" = "install" ] || [ "$1" = "i" ]; then
	sudo zypper install "${@:2}"
elif [ "$1" = "search" ] || [ "$1" = "s" ]; then
	zypper search "${@:2}"
elif [ "$1" = "remove" ] || [ "$1" = "rm" ]; then
	sudo zypper remove "${@:2}"
elif [ "$1" = "update" ] || [ "$1" = "u" ]; then
	update "${@:2}"
elif [ "$1" = "refresh" ]; then
	sudo zypper refresh
else 
	default
fi

