---

- name: Install emacs (fedora)
  tags: install
  dnf:
    name: emacs
    state: latest
  when: ansible_facts['os_family']|lower == 'redhat'
  become: yes
  become_user: root
  become_method: sudo

- name: Set init.el
  tags: config 
  ansible.builtin.file:
    src: '{{ inventory_dir }}/../emacs/init.el'
    dest: "{{ lookup('env', 'HOME') }}/.emacs.d/init.el"
    state: link
    force: yes
