---

- name: Install emacs
  tags: install
  ansible.builtin.package:
    name: emacs
    state: latest
  become: yes
  become_user: root
  become_method: sudo

- name: create config folder
  tags: config
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.emacs.d"
    state: directory

- name: Set init.el
  tags: config 
  ansible.builtin.file:
    src: '{{ inventory_dir }}/../emacs/init.el'
    dest: "{{ lookup('env', 'HOME') }}/.emacs.d/init.el"
    state: link
    force: yes
