---

- name: Install asdf (fedora)
  tags: install
  git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ lookup('env', 'HOME') }}/.asdf"
    version: v0.9.0

- name: Add asdf to .bashrc
  tags:
    - config
    - bashrc
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    line: '. $HOME/.asdf/asdf.sh'
    state: present

- name: Create plugins folder
  tags: config
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.asdf/plugins"
    state: directory
