---

# - name: Install SSH (fedora)
#  tags: install
#  ansible.builtin.package:
#    name: ssh
#    state: latest
#  become: yes

- name: Generate SSH key
  tags: config
  ansible.builtin.command:
    cmd: ssh-keygen -f "{{ user_home }}/.ssh/id_rsa" -N ""
    creates: "{{ user_home }}/.ssh/id_rsa*"
