---

- name: Install python3  (fedora)
  tags: install
  dnf:
    name: python3
    state: latest
  when: ansible_facts['os_family']|lower == 'redhat'
  become: yes
  become_user: root
  become_method: sudo