---

- name: Install VIM (fedora)
  tags: install
  ansible.builtin.package:
    name: vim
    state: latest
  become: yes
  become_user: root
  become_method: sudo

- name: Set vimrc
  tags: config
  ansible.builtin.copy:
    src: '{{ inventory_dir }}/../vim/vimrc'
    dest: "{{ user_home }}/.vimrc"

- name: Set VIM as default editor in .bashrc
  tags:
    - config
    - bashrc
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.bashrc"
    line: 'export EDITOR=vim'
    state: present
