#!/usr/bin/env bash


default() {
	echo -e "Small wrapper around pacman\n"

	echo "Choose one of:"
	echo -e " - install <args>"
	echo -e " - search  <args>"
	echo -e " - update  <args>"
	echo -e " - remove  <args>"
}

install() {
	sudo pacman -S "$@"
}

search() {
	pacman -Ss "$@"
}

update() {
	sudo pacman -Syu
}

remove() {
	sudo pacman -R "$@"
}

if [ $# -lt 1 ]; then
	default
elif [ $1 = "install" ]; then
	install "${@:2}"
elif [ $1 = "search" ]; then
	search "${@:2}"
elif [ $1 = "update" ]; then
	update
elif [ $1 = "remove" ]; then
	remove "${@:2}"
else
	default
fi

