---

- name: Install git (fedora)
  tags: install
  ansible.builtin.package:
    name: git
    state: latest
  become: yes
  become_user: root
  become_method: sudo

- name: Ensure .gitconfig is there
  tags: config
  ansible.builtin.copy:
    src: '{{ inventory_dir }}/../git/gitconfig'
    dest: "{{ user_home }}/.gitconfig"
